// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlwnpxzknnckusunjvaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsd25weHprbm5ja3VzdW5qdmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTI3NjUsImV4cCI6MjA2MDU2ODc2NX0.4YIB5n1qP2DcUHOE3vQtSoBfcxNONEVK5v4dBPZxO6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);